[package]
name = "eaf-rs"
version = "0.7.0"
edition = "2024"
authors = ["Jens Larsson <jens.dev@fastmail.com>"]
description = "Read/write ELAN files"
repository = "https://github.com/jenslar/eaf-rs"
keywords = ["elan", "eaf", "pfsx", "annotation", "xml"]
license-file = "MIT"

[dependencies]
blake3 = "1.8.4"
csv = "1.4"
log = "0.4.32"
mp4iter = {path = "../mp4iter"}
quick-xml = { version = "0.40.1", features = [ "serialize", "overlapped-lists" ] }
rayon = "1.12"
regex = "1.12.4"
serde = { version = "1.0.228", features = [ "derive" ] }
serde_json = "1.0.150"
termcolor = "1.4.1"
time = { version = "0.3.48", features = [ "formatting", "serde" ] }
tracing-subscriber = {version = "0.3.22", features = ["fmt", "time"]} # hide behind feature
# quick-xml = { version = "0.38.3", features = [ "serialize", "overlapped-lists" ] }
# quick-xml = { version = "0.39.2", features = [ "serialize", "overlapped-lists" ] }
unicode-segmentation = "1.12.0"
url = {version = "2.5.8", features = ["serde"]}
uuid = { version = "1.23.3", features = ["v4"]}
# mp4iter = {git = "https://github.com/jenslar/mp4iter.git"}
